export type WellKnownSecret =
  | "BUILD_CHUNK"
  | "TEXTURE_CHUNKS"
  | "TEMP"
  | "WOTB_SERVER"
  | "WOTB_VERSION"
  | "PUBLIC_WOTB_CLIENT"
  | "WOTB_USMAP"
  | "GOOGLE_APPLICATION_CREDENTIALS"
  | "PUBLIC_GOOGLE_ANALYTICS_PROPERTY_ID";
