// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v7.36.1
// source: description_definitions.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { I18nString } from "./i18n";

export const protobufPackage = "blitzkit";

export enum DescriptionSource {
  DESCRIPTION_SOURCE_BLITZ = 0,
  DESCRIPTION_SOURCE_WOT = 1,
}

export function descriptionSourceFromJSON(object: any): DescriptionSource {
  switch (object) {
    case 0:
    case "DESCRIPTION_SOURCE_BLITZ":
      return DescriptionSource.DESCRIPTION_SOURCE_BLITZ;
    case 1:
    case "DESCRIPTION_SOURCE_WOT":
      return DescriptionSource.DESCRIPTION_SOURCE_WOT;
    default:
      throw new globalThis.Error("Unrecognized enum value " + object + " for enum DescriptionSource");
  }
}

export function descriptionSourceToJSON(object: DescriptionSource): string {
  switch (object) {
    case DescriptionSource.DESCRIPTION_SOURCE_BLITZ:
      return "DESCRIPTION_SOURCE_BLITZ";
    case DescriptionSource.DESCRIPTION_SOURCE_WOT:
      return "DESCRIPTION_SOURCE_WOT";
    default:
      throw new globalThis.Error("Unrecognized enum value " + object + " for enum DescriptionSource");
  }
}

export interface DescriptionDefinitions {
  descriptions: { [key: number]: TankDescription };
}

export interface DescriptionDefinitions_DescriptionsEntry {
  key: number;
  value: TankDescription | undefined;
}

export interface TankDescription {
  text: I18nString | undefined;
  source: DescriptionSource;
}

function createBaseDescriptionDefinitions(): DescriptionDefinitions {
  return { descriptions: {} };
}

export const DescriptionDefinitions: MessageFns<DescriptionDefinitions> = {
  encode(message: DescriptionDefinitions, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    Object.entries(message.descriptions).forEach(([key, value]) => {
      DescriptionDefinitions_DescriptionsEntry.encode({ key: key as any, value }, writer.uint32(10).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DescriptionDefinitions {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDescriptionDefinitions();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          const entry1 = DescriptionDefinitions_DescriptionsEntry.decode(reader, reader.uint32());
          if (entry1.value !== undefined) {
            message.descriptions[entry1.key] = entry1.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DescriptionDefinitions {
    return {
      descriptions: isObject(object.descriptions)
        ? Object.entries(object.descriptions).reduce<{ [key: number]: TankDescription }>((acc, [key, value]) => {
          acc[globalThis.Number(key)] = TankDescription.fromJSON(value);
          return acc;
        }, {})
        : {},
    };
  },

  toJSON(message: DescriptionDefinitions): unknown {
    const obj: any = {};
    if (message.descriptions) {
      const entries = Object.entries(message.descriptions);
      if (entries.length > 0) {
        obj.descriptions = {};
        entries.forEach(([k, v]) => {
          obj.descriptions[k] = TankDescription.toJSON(v);
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DescriptionDefinitions>, I>>(base?: I): DescriptionDefinitions {
    return DescriptionDefinitions.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DescriptionDefinitions>, I>>(object: I): DescriptionDefinitions {
    const message = createBaseDescriptionDefinitions();
    message.descriptions = Object.entries(object.descriptions ?? {}).reduce<{ [key: number]: TankDescription }>(
      (acc, [key, value]) => {
        if (value !== undefined) {
          acc[globalThis.Number(key)] = TankDescription.fromPartial(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseDescriptionDefinitions_DescriptionsEntry(): DescriptionDefinitions_DescriptionsEntry {
  return { key: 0, value: undefined };
}

export const DescriptionDefinitions_DescriptionsEntry: MessageFns<DescriptionDefinitions_DescriptionsEntry> = {
  encode(message: DescriptionDefinitions_DescriptionsEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== 0) {
      writer.uint32(8).uint32(message.key);
    }
    if (message.value !== undefined) {
      TankDescription.encode(message.value, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DescriptionDefinitions_DescriptionsEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDescriptionDefinitions_DescriptionsEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.key = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = TankDescription.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DescriptionDefinitions_DescriptionsEntry {
    return {
      key: isSet(object.key) ? globalThis.Number(object.key) : 0,
      value: isSet(object.value) ? TankDescription.fromJSON(object.value) : undefined,
    };
  },

  toJSON(message: DescriptionDefinitions_DescriptionsEntry): unknown {
    const obj: any = {};
    if (message.key !== 0) {
      obj.key = Math.round(message.key);
    }
    if (message.value !== undefined) {
      obj.value = TankDescription.toJSON(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DescriptionDefinitions_DescriptionsEntry>, I>>(
    base?: I,
  ): DescriptionDefinitions_DescriptionsEntry {
    return DescriptionDefinitions_DescriptionsEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DescriptionDefinitions_DescriptionsEntry>, I>>(
    object: I,
  ): DescriptionDefinitions_DescriptionsEntry {
    const message = createBaseDescriptionDefinitions_DescriptionsEntry();
    message.key = object.key ?? 0;
    message.value = (object.value !== undefined && object.value !== null)
      ? TankDescription.fromPartial(object.value)
      : undefined;
    return message;
  },
};

function createBaseTankDescription(): TankDescription {
  return { text: undefined, source: 0 };
}

export const TankDescription: MessageFns<TankDescription> = {
  encode(message: TankDescription, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.text !== undefined) {
      I18nString.encode(message.text, writer.uint32(10).fork()).join();
    }
    if (message.source !== 0) {
      writer.uint32(16).int32(message.source);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TankDescription {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTankDescription();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.text = I18nString.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.source = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TankDescription {
    return {
      text: isSet(object.text) ? I18nString.fromJSON(object.text) : undefined,
      source: isSet(object.source) ? descriptionSourceFromJSON(object.source) : 0,
    };
  },

  toJSON(message: TankDescription): unknown {
    const obj: any = {};
    if (message.text !== undefined) {
      obj.text = I18nString.toJSON(message.text);
    }
    if (message.source !== 0) {
      obj.source = descriptionSourceToJSON(message.source);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TankDescription>, I>>(base?: I): TankDescription {
    return TankDescription.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TankDescription>, I>>(object: I): TankDescription {
    const message = createBaseTankDescription();
    message.text = (object.text !== undefined && object.text !== null)
      ? I18nString.fromPartial(object.text)
      : undefined;
    message.source = object.source ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string; value: unknown } ? { $case: T["$case"]; value?: DeepPartial<T["value"]> }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
