blank_issues_enabled: false

contact_links:
  - name: 🎮 Discord Server
    about: Got questions? We answer better on Discord!
    url: https://discord.gg/nDt7AjGJQH

  - name: ✉️ Email
    about: Reach out to BlitzKit formally through email.
    url: https://blitzkit.app/contact
