name: Build Assets

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0'

      - name: Get latest release info
        id: release
        run: |
          $RELEASE_JSON = Invoke-RestMethod -Uri https://api.github.com/repos/SteamRE/DepotDownloader/releases/latest
          Write-Output "##vso[task.setvariable variable=tag_name;isOutput=true]$($RELEASE_JSON.tag_name)"
          Write-Output "##vso[task.setvariable variable=download_url;isOutput=true]$($RELEASE_JSON.assets[0].browser_download_url)"

      - name: Download file as depotdownload.zip
        run: |
          $DOWNLOAD_URL = $env:download_url
          Invoke-WebRequest -Uri $DOWNLOAD_URL -OutFile depotdownload.zip

      - name: Extract zip file
        run: Expand-Archive -Path depotdownload.zip -DestinationPath .

      - name: Run DepotDownloader.dll
        run: |
          $DLL_PATH = ".\DepotDownloader.dll"
          dotnet $DLL_PATH
