name: CD Build Assets

on:
  push:
    branches: main
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GH_TOKEN }}
      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Setup DepotDownloader
        run: bun scripts/setupDepotDownloader.ts

      - name: Run DepotDownloader
        run: ./temp/depotDownloader/DepotDownloader.exe -os windows -app 444200 -username ${{ secrets.DEPOT_DOWNLOADER_USERNAME }} -password "${{ secrets.DEPOT_DOWNLOADER_PASSWORD }}"

      - name: Apply patches
        run: |
          $env:GH_TOKEN = "${{ secrets.GH_TOKEN }}" 
          $env:DISCORD_TOKEN = "${{ secrets.DISCORD_TOKEN }}" 
          $env:DATABASE_URL = "${{ secrets.DATABASE_URL }}" 
          $env:WOTB_DLC_CDN = "${{ secrets.WOTB_DLC_CDN }}"
          bun scripts/applyPatches.ts --depot

      - name: Build assets
        run: |
          $env:GH_TOKEN = "${{ secrets.GH_TOKEN }}" 
          $env:DISCORD_TOKEN = "${{ secrets.DISCORD_TOKEN }}" 
          $env:DATABASE_URL = "${{ secrets.DATABASE_URL }}" 
          $env:VIDEOS_SHEET = "${{ secrets.VIDEOS_SHEET }}" 
          $env:GOOGLE_APPLICATION_CREDENTIALS = "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"
          bun build:assets --all-targets --depot --production
