name: CD Docs

on:
  push:
    branches: main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Yarn
        run: npm install --location=global yarn

      - name: Use node_modules cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn

      - name: Build docs
        run: yarn build:docs

      - name: Configure pages
        uses: actions/configure-pages@v2

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist/docs

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1

      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: docs/.vitepress/dist
