name: CI Build Bot

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Yarn
        run: npm install --location=global yarn

      - name: Install dependencies
        run: yarn

      - name: Build Prisma
        run: yarn prisma generate

      - name: Build
        run: yarn build:bot --production

      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: bot
          path: dist/bot
