name: IDs

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  PUBLIC_ASSET_BRANCH: ${{ secrets.PUBLIC_ASSET_BRANCH }}
  PUBLIC_ASSET_REPO: ${{ secrets.PUBLIC_ASSET_REPO }}
  PUBLIC_WARGAMING_APPLICATION_ID: ${{ secrets.PUBLIC_WARGAMING_APPLICATION_ID }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GH_TOKEN }}

      - uses: oven-sh/setup-bun@v1
      - uses: arduino/setup-protoc@v3

      - name: Install dependencies
        run: bun install

      - name: Build protos
        run: bun run build:protos

      - name: Discover IDs
        run: bun build:ids --production
