name: Host

on:
  push:
    branches: main
  schedule:
    - cron: "0 */5 * * *"
  workflow_dispatch:
  release:
    types: [created, published, released, edited]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
  DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  PUBLIC_ASSET_REPO: ${{ secrets.PUBLIC_ASSET_REPO }}
  PUBLIC_ASSET_BRANCH: ${{ secrets.PUBLIC_ASSET_BRANCH }}
  PUBLIC_WARGAMING_APPLICATION_ID: ${{ secrets.PUBLIC_WARGAMING_APPLICATION_ID }}
  PUBLIC_ASSET_FAST_USER: ${{ secrets.PUBLIC_ASSET_FAST_USER }}
  PUBLIC_ASSET_FAST_REPO: ${{ secrets.PUBLIC_ASSET_FAST_REPO }}
  PUBLIC_PROMOTE_OPENTEST: ${{ secrets.PUBLIC_PROMOTE_OPENTEST }}
  ALLOW_ROBOTS: ${{ secrets.ALLOW_ROBOTS }}
  WOTB_GLOSSARY: ${{ secrets.WOTB_GLOSSARY }}
  PUBLIC_GOOGLE_TAG_MANAGER_ID: ${{ secrets.PUBLIC_GOOGLE_TAG_MANAGER_ID }}
  PUBLIC_GOOGLE_ANALYTICS_PROPERTY_ID: ${{ secrets.PUBLIC_GOOGLE_ANALYTICS_PROPERTY_ID }}
  GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
  WOTB_GLOSSARY_DOMAIN: ${{ secrets.WOTB_GLOSSARY_DOMAIN }}
  WOTB_GLOSSARY_PATH: ${{ secrets.WOTB_GLOSSARY_PATH }}
  PUBLIC_DISCORD_SERVER_ID: ${{ secrets.PUBLIC_DISCORD_SERVER_ID }}
  PUBLIC_ASSET_BASE: ${{ secrets.PUBLIC_ASSET_BASE }}
  PUBLIC_BRANCH: ${{ secrets.PUBLIC_BRANCH }}
  PUBLIC_GUIDE_WEBSITE: ${{ secrets.PUBLIC_GUIDE_WEBSITE }}
  SERVICING: ${{ secrets.SERVICING }}

jobs:
  host:
    runs-on: ubuntu-latest

    steps:
      - uses: oven-sh/setup-bun@v1
      #        with:
      #          bun-version: 1.1.33

      - name: Download release assets
        run: |
          DOWNLOAD_URL=$(curl -s https://api.github.com/repos/blitzkit/blitzkit/releases/latest \
            | grep "browser_download_url.*bot.zip" \
            | cut -d : -f 2,3 \
            | tr -d \")
          curl -L -o bot.zip $DOWNLOAD_URL
          mkdir -p dist/bot
          unzip bot.zip -d dist/bot

      - name: Install sharp
        run: bun init -y && bun add sharp

      - name: Move directories
        run: mv dist/bot/prisma .

      - name: Run bot
        run: bun run dist/bot/main.js
