name: Rating Europe

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'

jobs:
  host:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Generate leaderboard
        env:
          PUBLIC_ASSET_BRANCH: main
          PUBLIC_ASSET_REPO: ${{ secrets.PUBLIC_ASSET_REPO }}
          DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          PUBLIC_WARGAMING_APPLICATION_ID: ${{ secrets.PUBLIC_WARGAMING_APPLICATION_ID }}
          PUBLIC_ASSET_FAST_USER: ${{ secrets.PUBLIC_ASSET_FAST_USER }}
          PUBLIC_ASSET_FAST_REPO: ${{ secrets.PUBLIC_ASSET_FAST_REPO }}
        run: bun build:ratingleaderboard --region=eu
